# Site settings
title: Ali Hasan Mohiuddin
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ali Hasan Mohiuddin
user_description:
  A software developer who elegantly untangles complex problems, fueled by a
  blend of cookies, code, and the relentless pursuit of innovation—even as the
  shadow of imposter syndrome looms, reminding me that every challenge is a step
  towards mastering the craft.
user_title: Software Engineer
email: amohiud@gmu.edu
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
linkedin_username: somethingdevs
github_username: somethingdevs
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']
